-- Insert sample Kenyan service providers
INSERT INTO public.service_providers (
  user_id, name, service_type, location, experience_years, availability, gender, 
  bio, contact_info, hourly_rate, languages
) VALUES 
(
  gen_random_uuid(),
  'Mary Wanjiku Kamau',
  'maid',
  'Eastleigh, Nairobi',
  5,
  'available',
  'female',
  'Experienced house manager with 5 years of service in Nairobi families. I specialize in deep cleaning, laundry, and organizing. Very reliable and trustworthy. Available for both part-time and full-time positions.',
  '+254712345678',
  'KSH 800',
  ARRAY['English', 'Swahili', 'Kikuyu']
),
(
  gen_random_uuid(),
  'James Ochieng Otieno',
  'watchman',
  'South B, Nairobi',
  8,
  'available',
  'male',
  'Professional security guard with 8 years experience. Trained in first aid and emergency response. Have worked in residential apartments and commercial buildings. Very vigilant and responsible.',
  '+254723456789',
  'KSH 1200',
  ARRAY['English', 'Swahili', 'Luo']
),
(
  gen_random_uuid(),
  'Grace Akinyi Ouma',
  'nanny',
  'Karen, Nairobi',
  3,
  'available',
  'female',
  'Loving and caring nanny with experience taking care of children aged 6 months to 12 years. Certified in child first aid. I enjoy reading stories, playing educational games, and helping with homework.',
  '+254734567890',
  'KSH 600',
  ARRAY['English', 'Swahili', 'Luo']
),
(
  gen_random_uuid(),
  'Samuel Kiprotich Chelimo',
  'driver',
  'Westlands, Nairobi',
  12,
  'busy',
  'male',
  'Professional driver with 12 years experience. Clean driving record with valid PSV license. Familiar with all Nairobi routes and excellent customer service. Available for personal, family, and business driving.',
  '+254745678901',
  'KSH 1000',
  ARRAY['English', 'Swahili', 'Kalenjin']
),
(
  gen_random_uuid(),
  'Florence Nyokabi Mwangi',
  'cook',
  'Kikuyu, Kiambu',
  6,
  'available',
  'female',
  'Skilled cook specializing in both local Kenyan dishes and international cuisine. Can prepare meals for special diets including vegetarian and diabetic-friendly meals. Very clean and organized in the kitchen.',
  '+254756789012',
  'KSH 700',
  ARRAY['English', 'Swahili', 'Kikuyu']
),
(
  gen_random_uuid(),
  'David Maina Githuku',
  'gardener',
  'Kileleshwa, Nairobi',
  10,
  'available',
  'male',
  'Experienced gardener and landscaper. Skilled in growing vegetables, flowers, and maintaining lawns. Can design beautiful gardens and maintain existing ones. Also do tree trimming and pest control.',
  '+254767890123',
  'KSH 900',
  ARRAY['English', 'Swahili', 'Kikuyu']
),
(
  gen_random_uuid(),
  'Ruth Mumbua Musyoka',
  'cleaner',
  'Buruburu, Nairobi',
  4,
  'available',
  'female',
  'Thorough and reliable cleaner with attention to detail. Experienced in office cleaning, house cleaning, and post-construction cleanup. Use eco-friendly cleaning products and always ensure client satisfaction.',
  '+254778901234',
  'KSH 500',
  ARRAY['English', 'Swahili', 'Kamba']
),
(
  gen_random_uuid(),
  'Peter Wekesa Makokha',
  'handyman',
  'Kasarani, Nairobi',
  7,
  'available',
  'male',
  'Skilled handyman with expertise in plumbing, electrical work, carpentry, and general repairs. Can fix anything from leaky taps to electrical installations. Fair prices and quality workmanship guaranteed.',
  '+254789012345',
  'KSH 1500',
  ARRAY['English', 'Swahili', 'Luhya']
),
(
  gen_random_uuid(),
  'Agnes Chebet Korir',
  'security_guard',
  'Langata, Nairobi',
  4,
  'not_available',
  'female',
  'Female security guard with training in crowd control and surveillance. Currently employed but looking for part-time weekend opportunities. Professional and vigilant with excellent communication skills.',
  '+254790123456',
  'KSH 1100',
  ARRAY['English', 'Swahili', 'Kalenjin']
),
(
  gen_random_uuid(),
  'Michael Okoth Owino',
  'driver',
  'Kibera, Nairobi',
  9,
  'available',
  'male',
  'Reliable driver with experience in both personal and commercial driving. Familiar with Nairobi traffic patterns and alternative routes. Available for school runs, shopping trips, and business meetings.',
  '+254701234567',
  'KSH 800',
  ARRAY['English', 'Swahili', 'Luo']
);